// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsW5GFwVkV7ABDtjIwJE0ECr4A-dMzY-c',
    appId: '1:121784530712:web:09e4cd4cea0200b564906d',
    messagingSenderId: '121784530712',
    projectId: 'spotify-copy-03',
    authDomain: 'spotify-copy-03.firebaseapp.com',
    storageBucket: 'spotify-copy-03.appspot.com',
    measurementId: 'G-9T7G3V72BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvksAfjlNSZN1Z2oYU_kg0Ag_M5vv22K8',
    appId: '1:121784530712:android:fb94c79837f652f364906d',
    messagingSenderId: '121784530712',
    projectId: 'spotify-copy-03',
    storageBucket: 'spotify-copy-03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu84HCzHv_gT3BlE7yuC_q8O8u960oGFA',
    appId: '1:121784530712:ios:6ddfa158d113cec864906d',
    messagingSenderId: '121784530712',
    projectId: 'spotify-copy-03',
    storageBucket: 'spotify-copy-03.appspot.com',
    iosClientId: '121784530712-jt2q508h2hjd8f3qq9hc1kr1iq9d77qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyCopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu84HCzHv_gT3BlE7yuC_q8O8u960oGFA',
    appId: '1:121784530712:ios:6ddfa158d113cec864906d',
    messagingSenderId: '121784530712',
    projectId: 'spotify-copy-03',
    storageBucket: 'spotify-copy-03.appspot.com',
    iosClientId: '121784530712-jt2q508h2hjd8f3qq9hc1kr1iq9d77qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyCopy',
  );
}
